POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Binh Nguyen",
  "dateOfBirth": "2000-23-03",
  "ssn": "123456-7cn",
  "gender": "male" ,
  "occupation": "student"
}
