
### TODO: GET LIST OF PEOPLE IN THE PHONEBOOK (200)
GET http://localhost:3001/api/persons

### TODO: GET A SPECIFIC PERSON INFO FROM THE PHONEBOOK (200)
GET http://localhost:3001/api/persons/6436c0d9e40c19c32430348c

### TODO: GET A SPECIFIC PERSON INFO FROM THE PHONEBOOK (404) - not found
GET http://localhost:3001/api/persons/6436bff413a632e599cb4a92

### TODO: POST A PERSON IN TO THE PHONEBOOK (200)
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Ben Nguyen",
    "number": "090-1234125"
}

### TODO: POST A PERSON IN TO THE PHONEBOOK (400) - invalid phone number
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Binh Nguyen",
    "number": "0905134125"
}

### TODO: DELETE A PERSON IN THE PHONEBOOK (200)
DELETE http://localhost:3001/api/persons/2

### TODO: DELETE A PERSON IN THE PHONEBOOK (400) - malformatted id
DELETE http://localhost:3001/api/persons/2

### TODO: UPDATE A PERSON'S NUMBER IN THE PHONEBOOK (200)
PUT http://localhost:3001/api/persons/64460089bfa67364f2c0d7b6
Content-type: application/json

{
    "name": "Ben Nguyen",
    "number": "090-6959527"
}

### TODO: UPDATE A PERSON'S NUMBER IN THE PHONEBOOK (200)
PUT http://localhost:3001/api/persons/64460089bfa67364f2c0d7b6
Content-type: application/json

{
    "name": "Binh Nguyen",
    "number": "090-6959527"
}

### TODO: UPDATE A PERSON'S NUMBER IN THE PHONEBOOK (400)
PUT http://localhost:3001/api/persons/64460089bfa67364f2c0d7b6
Content-type: application/json

{
    "name": "Binh Nguyen",
    "number": "0906959527"
}