GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Binh Nguyen",
    "number": "0905134125"
}

###
DELETE http://localhost:3001/api/persons/2